### PR TITLE
Feat/voice conferences

### PR DESCRIPTION
**Pull request by Dovchik**
Covers https://developers.sinch.com/docs/voice/api-reference/voice/tag/Conferences/

### CODE REVIEW

**Review by JPPortier — COMMENTED** [review]
My aim for Java SDK is to have the `callout request` dedicated to Conference defined.

To stay stitched to the developer documentation which duplicate it (and OAS file too by using 2 tags for same endpoints)

What do you think about having a dedicated `Sinch.Voice.Conferences.call (ConferenceCalloutRequest)` function defined but just a helper/passtrough onto `Sinch.Voice.Callouts.Conference` ?

**Comment by Dovchik** [comment]
> My aim for Java SDK is to have the `callout request` dedicated to Conference defined.
> 
> To stay stitched to the developer documentation which duplicate it (and OAS file too by using 2 tags for same endpoints)
> 
> What do you think about having a dedicated `Sinch.Voice.Conferences.call (ConferenceCalloutRequest)` function defined but just a helper/passtrough onto `Sinch.Voice.Callouts.Conference` ?

Makes sense as neat function, but I'll like to add it to backlog first with out of scope of the pr

**Comment by JPPortier** [comment]
@Dovchik build for .NET 7 and 8 are failing; is this is having to be fixed ?

**Comment by Dovchik** [comment]
@JPPortier yeah, it's usual pre Doppelgänger merge build

**Review by JPPortier — APPROVED** [review]

**Pull request merged**
